- name: install micork8s in Master node
  hosts: control_plane
  become: true
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist
        
    - name: Ensure snapd is installed
      ansible.builtin.package:
        name: snapd
        state: present
    
    - name: Install microk8s using snap
      ansible.builtin.command:
        cmd: snap install microk8s --classic --channel=1.30/stable
      register: install_output

    - name: Check if Microk8s is running
      ansible.builtin.command:
        cmd: microk8s status --wait-ready
      register: microk8s_status
      until: microk8s_status.rc == 0
      retries: 2
      delay: 10

    - name: Enable microk8s add-on cert-manager
      ansible.builtin.command:
        cmd: microk8s enable cert-manager
      register: cert_manager_output