- name: Install Cilium
  hosts: master_nodes
  become: true
  tasks:
    - name: Download Cilium CLI
      ansible.builtin.get_url:
        url: https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz
        dest: /usr/local/bin/cilium-linux-amd64.tar.gz
        mode: '0644'

    - name: Extract and move Cilium CLI
      ansible.builtin.unarchive:
        src: /usr/local/bin/cilium-linux-amd64.tar.gz
        dest: /usr/local/bin/
        remote_src: true
      args:
        creates: /usr/local/bin/cilium

    - name: Deploy Cilium network plugin
      ansible.builtin.command: /usr/local/bin/cilium install
      changed_when: false
      register: cilium_install
      notify: Configure Cilium

  handlers:
    - name: Configure Cilium
      ansible.builtin.command: >
        /usr/local/bin/cilium config enable-ipv4=true &&
        /usr/local/bin/cilium config cluster-pool-ipv4-cidr=10.244.0.0/16
      changed_when: false
