- name: Install htop package
  hosts: nodes
  become: true # root 권한으로 실행
  tasks:
    - name: Install htop
      ansible.builtin.apt:
        name: htop
        state: present
        update_cache: true
