- name: Reset Kubernetes cluster
  hosts: nodes
  become: true
  tasks:
    - name: Reset kubeadm
      ansible.builtin.command: kubeadm reset -f
      register: result
      changed_when: result.rc == 0
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Flush iptables rules
      ansible.builtin.command: iptables -F
      changed_when: false

    - name: Flush iptables NAT table
      ansible.builtin.command: iptables -t nat -F
      changed_when: false

    - name: Flush iptables mangle table
      ansible.builtin.command: iptables -t mangle -F
      changed_when: false


    - name: Delete all iptables chains
      ansible.builtin.command: iptables -X
      changed_when: false

    - name: Remove CNI configurations
      ansible.builtin.file:
        path: /etc/cni/net.d
        state: absent

    - name: Remove Kubernetes configuration directory
      ansible.builtin.file:
        path: /etc/kubernetes
        state: absent

    - name: Remove Kubernetes .kube directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: absent

    - name: Remove etcd data directory
      ansible.builtin.file:
        path: /var/lib/etcd
        state: absent
