- name: Install and Configure Neovim
  hosts: localhost
  vars:
    neovim_config_dir: "/home/kkamji/.config/nvim"
    neovim_init_file: "{{ neovim_config_dir }}/init.lua"
    neovim_init_content: |
      -- ~/.config/nvim/init.lua
      vim.g.mapleader = " " -- 리더 키를 스페이스로 설정 (lazy.nvim 설정 전에 필요)

      -- 기존 설정 유지
      vim.opt.number = false       -- 줄 번호 표시
      vim.opt.autoindent = true    -- 자동 들여쓰기
      vim.opt.tabstop = 2          -- 탭 크기
      vim.opt.shiftwidth = 2       -- 자동 들여쓰기 크기
      vim.opt.smarttab = true      -- 스마트 탭
      vim.opt.softtabstop = 2      -- 편집할 때 탭 크기
      vim.opt.termguicolors = true -- 터미널 색상 지원
      vim.opt.mouse = ""

      -- lazy.nvim 설치
      local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
      if not vim.loop.fs_stat(lazypath) then
        vim.fn.system({
          "git",
          "clone",
          "--filter=blob:none",
          "https://github.com/folke/lazy.nvim.git",
          "--branch=stable",
          lazypath,
        })
      end
      vim.opt.rtp:prepend(lazypath)

      -- 핵심 플러그인만 설치
      require("lazy").setup({
        -- 테마
        {
          "folke/tokyonight.nvim",
          lazy = false,
          priority = 1000,
          config = function()
            vim.cmd[[colorscheme tokyonight]]
          end,
        },

        -- 파일 탐색기
        {
          "nvim-neo-tree/neo-tree.nvim",
          branch = "v3.x",
          dependencies = {
            "nvim-lua/plenary.nvim",
            "nvim-tree/nvim-web-devicons",
            "MunifTanjim/nui.nvim",
          },
        },

        -- 상태바
        {
          'nvim-lualine/lualine.nvim',
          dependencies = { 'nvim-tree/nvim-web-devicons' },
          config = function()
            require('lualine').setup {
              options = {
                theme = 'tokyonight'
              }
            }
          end
        },
      })

      -- 기본 키매핑
      local map = vim.keymap.set
      local opts = { noremap = true, silent = true }

      -- Neo-tree 토글
      map('n', '<leader>e', ':Neotree toggle<CR>', opts)

      -- 창 이동
      map('n', '<C-h>', '<C-w>h', opts)
      map('n', '<C-j>', '<C-w>j', opts)
      map('n', '<C-k>', '<C-w>k', opts)
      map('n', '<C-l>', '<C-w>l', opts)

  tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install Neovim
      become: true
      ansible.builtin.apt:
        name: neovim
        state: present

    - name: Create Neovim configuration directory
      ansible.builtin.file:
        path: "{{ neovim_config_dir }}"
        state: directory
        mode: '0755'
        owner: kkamji
        group: kkamji
      become: true
      become_user: kkamji

    - name: Create init.lua file
      ansible.builtin.copy:
        dest: "{{ neovim_init_file }}"
        content: "{{ neovim_init_content }}"
        owner: kkamji
        group: kkamji
        mode: '0644'
      become: true
      become_user: kkamji
